// Generated by https://pagedraw.io/pages/12255
import React from 'react';
import './component.css';


export default class Pd1129433611816909 extends React.Component {
  render() {
    return (
      <div className="pd1129433611816909-component-1">
          <div className="pd1129433611816909-0" />
          <div className="pd1129433611816909-1">
              <div className="pd1129433611816909-receipt-bg-1">
                  <div className="pd1129433611816909-1-0-0">
                      <div className="pd1129433611816909-1-0-0-0">
                          <div className="pd1129433611816909-1-0-0-0-0">
                              <div className="pd1129433611816909-payment-receipt-title-6">
                                  PAYMENT RECEIPT
                              </div>
                          </div>
                          <div className="pd1129433611816909-1-0-0-0-1">
                              <div className="pd1129433611816909-payer-name-1">
                                  eostribeprod
                              </div>
                          </div>
                      </div>
                      <div className="pd1129433611816909-logo-1" />
                      <div className="pd1129433611816909-1-0-0-2">
                          <div className="pd1129433611816909-1-0-0-2-0">
                              <div className="pd1129433611816909-timestamp-8">
                                  <div>Sep-05-2018</div>
                                  <div>{"10:55:06 AM"}</div>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="pd1129433611816909-1-0-1">
                      <div className="pd1129433611816909-transaction-id-7">
                          +++++++++++++++++++++++++++++++++++++
                      </div>
                  </div>
                  <div className="pd1129433611816909-1-0-2">
                      <div className="pd1129433611816909-note-title-9">
                          {"NOTE:"}
                      </div>
                  </div>
                  <div className="pd1129433611816909-1-0-3">
                      <div className="pd1129433611816909-note-body-text-8">
                          {"Congratulations! You’ve just violated the constitution by sending money to another block producer. Prepare to get roasted on social media and fall out of the rankings."}
                      </div>
                  </div>
                  <div className="pd1129433611816909-1-0-4">
                      <div className="pd1129433611816909-transaction-id-4">
                          +++++++++++++++++++++++++++++++++++++
                      </div>
                  </div>
                  <div className="pd1129433611816909-1-0-5">
                      <div className="pd1129433611816909-1-0-5-0">
                          <div className="pd1129433611816909-1-0-5-0-0">
                              <div className="pd1129433611816909-triangle-icon-6">
                                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 15" className="pd1129433611816909-1-0-5-0-0-0-0">
                                      <polygon points="0 15 18 0 18 15" className="pd1129433611816909-1-0-5-0-0-0-0-0" />
                                  </svg>
                              </div>
                          </div>
                      </div>
                      <div className="pd1129433611816909-1-0-5-1">
                          <div className="pd1129433611816909-1-0-5-1-0">
                              <div className="pd1129433611816909-recipient-title-1">
                                  RECIPIENT
                              </div>
                          </div>
                          <div className="pd1129433611816909-1-0-5-1-1">
                              <div className="pd1129433611816909-eosnationftw-6">
                                  eosnationftw
                              </div>
                          </div>
                      </div>
                      <div className="pd1129433611816909-1-0-5-2">
                          <div className="pd1129433611816909-1-0-5-2-0">
                              <div className="pd1129433611816909-triangle-icon-8">
                                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 16" className="pd1129433611816909-1-0-5-2-0-0-0">
                                      <polygon points="0 16 18 0 18 16" className="pd1129433611816909-1-0-5-2-0-0-0-0" />
                                  </svg>
                              </div>
                          </div>
                      </div>
                      <div className="pd1129433611816909-1-0-5-3">
                          <div className="pd1129433611816909-1-0-5-3-0">
                              <div className="pd1129433611816909-amount-title-1">
                                  AMOUNT
                              </div>
                          </div>
                          <div className="pd1129433611816909-1-0-5-3-1">
                              <div className="pd1129433611816909-amount-total-9">
                                  $1337.01
                              </div>
                          </div>
                      </div>
                      <div className="pd1129433611816909-1-0-5-4">
                          <div className="pd1129433611816909-1-0-5-4-0">
                              <div className="pd1129433611816909-triangle-icon-3">
                                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 15" className="pd1129433611816909-1-0-5-4-0-0-0">
                                      <polygon points="0 15 18 0 18 15" className="pd1129433611816909-1-0-5-4-0-0-0-0" />
                                  </svg>
                              </div>
                          </div>
                      </div>
                      <div className="pd1129433611816909-1-0-5-5">
                          <div className="pd1129433611816909-1-0-5-5-0">
                              <div className="pd1129433611816909-purchase-title-1">
                                  PURCHASE
                              </div>
                          </div>
                          <div className="pd1129433611816909-1-0-5-5-1">
                              <div className="pd1129433611816909-purchase-type-5">
                                  Services
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="pd1129433611816909-1-0-6">
                      <div className="pd1129433611816909-transaction-id-0">
                          +++++++++++++++++++++++++++++++++++++
                      </div>
                  </div>
                  <div className="pd1129433611816909-1-0-7">
                      <div className="pd1129433611816909-transaction-id-3">
                          <div>{"Transaction id:"}</div>
                          <br/>
                          <div>9eca089b53133bf8dd3384178fb7e8abac956a4a8506b77987361c64c477ea54</div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="pd1129433611816909-2" />
          <div className="pd1129433611816909-3">
              <div className="pd1129433611816909-3-0" />
              <div className="pd1129433611816909-sponsors-3">
                  <div className="pd1129433611816909-3-1-0">
                      <a href="http://www.uwyo.edu/uw/news/2018/06/blockchain-hackathon-event-poised-to-elevate-uws-technology-profile.html" target="_blank" className="pd1129433611816909-3-1-0-0">
                          <div className="pd1129433611816909-uw-l-9" />
                      </a>
                      <a href="https://www.eosnation.io/" target="_blank" className="pd1129433611816909-3-1-0-1">
                          <div className="pd1129433611816909-eos-nation-logo-2" />
                      </a>
                      <a href="https://eostribe.io" target="_blank" className="pd1129433611816909-3-1-0-2">
                          <div className="pd1129433611816909-eos-tribe-logo-9" />
                      </a>
                  </div>
              </div>
              <div className="pd1129433611816909-3-2" />
          </div>
          <div className="pd1129433611816909-4">
              <div className="pd1129433611816909-4-0" />
              <div className="pd1129433611816909-footer-text-7">
                  A collaboration of EOS Tribe + EOS Nation at the 2018 Wyoming Hackathon
              </div>
              <div className="pd1129433611816909-4-2" />
          </div>
      </div>
    );
  }
};
